### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by anadb** [AppFlowy-IO/AppFlowy-Cloud#124]
I followed the instructions from deployment guide. However when I am trying to reach the server I see "Page not found".

It seems that AppFlowy wasn't integrated with my server, but there is nothing in documentation about that.

What should I do?

**Comment by speed2exe** [comment]
Hi @anadb! Thank you for trying out.
- You mention "AppFlowy wasn't integrated with my server", are you using the AppFlowy Desktop Application from https://github.com/AppFlowy-IO/AppFlowy? If so, this is not integrated at the moment, however we are working on it. In the meantime, you may want to check out https://docs.appflowy.io/docs/guides/appflowy/appflowy-with-supabase
- This project is still in development and will eventually provide alternative self-hosting solution without supabase.
 
 I would be happy to answer any follow up questions

**Comment by anadb** [comment]
Hi,

Thank you for your kind responce. Yes I am using AppFlowy Desktop Application. I had a quick look on a documentation on hosting AppFlowy using supabase and found it quite complicated. Do you have step by step guide how to do it including supabase installation?

**Comment by speed2exe** [comment]
Hi @anadb, as you scroll the documentations, there's a section on how you can self-host: 
https://docs.appflowy.io/docs/guides/appflowy/appflowy-with-supabase#how-to-self-host-appflowy-with-supabase

**Comment by Tameflame** [comment]
Hey, hopping onto this issue to ask about the following related problem:

I managed to deploy the cloud server via the deployment guide (so not the supabase guide), but I'm unable to login with the credentials I set into my .env file (error shown below). Could I ask if there's a way to solve? Or is this just because this feature is still being developed and it's just not ready yet.

![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/26692217/f19d1dd3-8532-4544-9870-190555bd787b)

```# This file is used to set the environment variables for local development
# Copy this file to .env and change the values as needed
 
# authentication key, change this and keep the key safe and secret
# self defined key, you can use any string
GOTRUE_JWT_SECRET=password1234
 
# user sign up will automatically be confirmed if this is set to true
GOTRUE_MAILER_AUTOCONFIRM=false
 
# if you enable mail confirmation, you need to set the SMTP configuration below
GOTRUE_SMTP_HOST=smtp.gmail.com
GOTRUE_SMTP_PORT=465
GOTRUE_SMTP_USER=email_sender@some_company.com
GOTRUE_SMTP_PASS=email_sender_password
GOTRUE_SMTP_ADMIN_EMAIL=comp_admin@@some_company.com
 
# gotrue admin
GOTRUE_ADMIN_EMAIL=admin@example.com
GOTRUE_ADMIN_PASSWORD=password1234
 
# clicking on email verification link will redirect to this host
# change this to your own domain where you host the docker-compose or gotrue
API_EXTERNAL_URL=http://localhost:9998
 
# url to the postgres database
DATABASE_URL=postgres://postgres:password@localhost:5433/postgres
# uncomment this to enable build without database
# .sqlx files must be pregenerated
SQLX_OFFLINE=false
 
# Google OAuth2
GOTRUE_EXTERNAL_GOOGLE_ENABLED=false
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
GOTRUE_EXTERNAL_GOOGLE_SECRET=
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://localhost:9998/callback
# GitHub OAuth2
GOTRUE_EXTERNAL_GITHUB_ENABLED=false
GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=
GOTRUE_EXTERNAL_GITHUB_SECRET=
GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=http://localhost:9998/callback
# Discord OAuth2
GOTRUE_EXTERNAL_DISCORD_ENABLED=false
GOTRUE_EXTERNAL_DISCORD_CLIENT_ID=
GOTRUE_EXTERNAL_DISCORD_SECRET=
GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI=http://localhost:9998/callback
# File Storage
USE_MINIO=true
# MINIO_URL=http://localhost:9000 # change this if you are using a different address for minio
AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=minioadmin
AWS_S3_BUCKET=appflowy
AWS_REGION=us-east-1
 
RUST_LOG=info
 
# PgAdmin
PGADMIN_DEFAULT_EMAIL=admin@example.com
PGADMIN_DEFAULT_PASSWORD=password1234
 
# Portainer (username: admin)
PORTAINER_PASSWORD=password1234
 
# Grafana Dashboard
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=password
 ```

**Comment by speed2exe** [comment]
Hi @Tameflame

Thank you for the interest in Appflowy Cloud and highlighting the issue.
Firt and foremost, this is still in development for the next iteration of self hosting appflowy cloud, so it is not ready yet to be used or integrated with the currently offline AppFlowy Desktop Application.

- For the issue you have faced, it's probably because you did not set up the SMTP to send email.
One possible solution is to set `GOTRUE_MAILER_AUTOCONFIRM` to be true before you deploy, a clean redeploy will be preferred.
Nevertheless, we are currently working on this and will be fixed in the subsequent iterations.
Documentations will also be improved.

I'd be happy to answer any further questions if you've got any.

**Comment by speed2exe** [comment]
Closing this issue. @Tameflame Feel free to reopen if issue still happens.
