### ISSUE TITLE
[Bug] The user doesn't delete when deleting from the admin web

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy-Cloud#187]
The user doesn't delete when deleting from admin web

<img width="1434" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/86001920/b40883a7-f298-41bb-bfa2-8ab91850309e">

<img width="1594" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/86001920/88a110f9-a307-4bbc-b480-a501dfbc09c8">

**Comment by speed2exe** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/33050391/654c45d5-4e21-4465-80ce-c20f95ba2422)

Root Cause:

- This happens because the changes (BYPASSRLS) in schema is not reapplied, as when postgresq restart, it does not run the init script again. The exact commit that was required was below.
https://github.com/AppFlowy-IO/AppFlowy-Cloud/commit/3890f5d306c399f7ec9311a432784f8a7aa4ed7f

- Only happens for user who have existing AppFlowy Cloud deploy and upgrade from before the commit above.
