### ISSUE TITLE
[FR] A quick setup guide for gotrue would be very useful

### ISSUE THREAD

**Issue by gargolito** [AppFlowy-IO/AppFlowy-Cloud#218]
**Use case**

As an user unfamiliar with supabase, it would be very useful to have a basic step-by-step setup for *gotrue*. The current documentation takes *gotrue* as a given, but in my case I had not even heard of it. Since this is used to handle authentication and authorization - as far as I can tell - the application will not run without it, it would be very helpful for those of use who want to test appflowy if we could have a quick guide for configuring the requirements.

If possible, maybe make it ***not a requirement*** for dev builds?

**what types of users can benefit from using your proposed feature**
Anyone that would like to test appflowy-cloud in their local docker environment without incurring the expense of deploying it to the cloud.

**Comment by speed2exe** [comment]
Hi, thanks for the feedback! I'll provide some explanations here.

Indeed GoTrue is required because it simplifies the implementation of various auth method such as:
- Email Verification
- OAuth2
- SAML

We do understand that it is some hassle to set up either of the auth above auth method, so for quick testing, 
There is an environmental variable: `GOTRUE_MAILER_AUTOCONFIRM`, which you can set to `false`
This will allow any email to be registered without the need for any form of verification. 
You can keep everything else pretty much default and it should run just fine.

The purpose of cloud is for data sync across devices and team collaboration, it only make sense for deployment in cloud for practical use.
If you wish to deploy on local machine for testing, changing `GOTRUE_MAILER_AUTOCONFIRM` should be good.

That being said, documentations will be improved for local testing and for setting up the GoTrue.

**Comment by gargolito** [comment]
Awesome. Thanks for your reply.

Btw, I have a pseudo-cloud work around. I host many apps on a home server
and haproxy in a ec2 instance with a tinc VPN to between them. I use a
wildcard letsencrypt certificate. This lets me use dockerized apps to keep
my data in sync no matter where I am.


I'm the only user so capacity is not an issue for me.

Best regards,

Anthony Camilo

**Comment by johanneshiry** [comment]
Hi @speed2exe - first thanks a lot for your efforts. I am super excited to run AppFlowy(Cloud) for a small team! 🚀 

One question though: AFAIU we currently have auth mechanisms available for google, discord and github. However, I would love to be able to create self-hosted, AppFlowy only accounts for the team members. 

- Is there any chance to login w/o google, github or discord directly in the desktop app? 

I was able to get the app opened with local user credentials through clicking a link in the backend of AppFlowyCloud after logging in as admin created user and already verified e-mail. But it seems like there is currently no way to achieve this in the desktop app. Did I miss something or is this not available (yet?)?

Please let me know if this questions is to far away from the topic here and should be discussed in a new issue. Thanks a lot!

**Comment by speed2exe** [comment]
@johanneshiry 
Hi, thanks for trying out AppFlowy Cloud.
If you are already able to login as admin, you can create other user in the admin page. (there is a top right corner red color "Admin", after you press, on the left, there will be a option where you can add other users).
Alternatively, you can also invite other user by sending confirmation to their email (requires SMTP setup).

![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/33050391/877a3f4d-3742-4358-9ca0-0d98cb84a654)

![image](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/33050391/44784811-fd69-4dd7-a614-31e6a2210c5f)

Feel free to let me know if you have more questions

**Comment by johanneshiry** [comment]
@speed2exe amazing, thanks a lot! 

Really looking forward on the email and password login feature, that is currently WIP. Having that would be super helpful for our setup! Will keep an eye on that ;-)

**Comment by appflowy** [comment]
I will close this FR. Feel free to reopen
