### ISSUE TITLE
[Bug] Could not send workspace invite mail

### ISSUE THREAD

**Issue by Aliang-code** [AppFlowy-IO/AppFlowy-Cloud#553]
**Describe the bug**
When invite member to my workspace on app, by default setting appflowy cloud will report log such as
``` [Failed to send workspace invite email: Connection error: Connection error] ```
Then I checked the code I found that some variables were not set at [docker-compose-ci.yml]
src/config/config.rs
```
mailer: MailerSetting {
      smtp_host: get_env_var("APPFLOWY_MAILER_SMTP_HOST", "smtp.gmail.com"),
      smtp_username: get_env_var("APPFLOWY_MAILER_SMTP_USERNAME", "sender@example.com"),
      smtp_password: get_env_var("APPFLOWY_MAILER_SMTP_PASSWORD", "password").into(),
    },
 ```
so i put these variables into docker-compose.yml and set in .env file use my smtp config
```
# AppFlowy Cloud Mailer
APPFLOWY_MAILER_SMTP_HOST=smtp.gmail.com
APPFLOWY_MAILER_SMTP_USERNAME=email_sender@some_company.com
APPFLOWY_MAILER_SMTP_PASSWORD=email_sender_password
```
but it still not working
```
Failed to send workspace invite email: permanent error (553): Mail from must equal authorized user\n\nCaused by:\n    Mail from must equal authorized user\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: appflowy_cloud::biz::workspace::ops::invite_workspace_members::{{closure}}::{{closure}}::{{closure}}::{{closure}}\n   2: tokio::runtime::task::raw::poll\n   3: std::sys_common::backtrace::__rust_begin_short_backtrace\n   4: core::ops::function::FnOnce::call_once{{vtable.shim}}\n   5: std::sys::pal::unix::thread::Thread::new::thread_start\n   6: <unknown>\n   7: clone
```
Finally I found out that the sender was not using user defined configuration
src/mailer.rs
![图片](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/30334745/e6b61c5c-d6fc-48cc-afb8-0213b1c3b57c)

I'm not good at using rust, Is my judgment correct? 
Hope fix soon, thx

**To Reproduce**
1. Go to settings
2. Click on member
3. add other email to send invite
4. See server log in appflowy cloud

**Expected behavior**
Correctly use user configuration to send invitation emails.

**Comment by Aliang-code** [comment]
Another issue is that it is not possible to resend invite mail, even if the email fails, or delete the invited users

**Comment by speed2exe** [comment]
thank you for the feedback, we'll improve on the behaviour. as a workaround, the invitation is still pending. so you can log in to the admin portal with the account that is invited, go to 'invite' and accept the invitation

**Comment by Aliang-code** [comment]
> thank you for the feedback, we'll improve on the behaviour. as a workaround, the invitation is still pending. so you can log in to the admin portal with the account that is invited, go to 'invite' and accept the invitation @Aliang-code

Yes, that's all I can do now

**Comment by almereyda** [comment]
As I am wondering, since you mention it twice, please allow me to ask: how come you are you using docker-compose-ci.yml and not the regular manifest without -ci?

**Comment by Aliang-code** [comment]
> As I am wondering, since you mention it twice, please allow me to ask: how come you are you using docker-compose-ci.yml and not the regular manifest without -ci?

Sorry, I wrote the wrong filename, actually I used docker-compose.yml

**Comment by xavier-hernandez** [comment]
> thank you for the feedback, we'll improve on the behaviour. as a workaround, the invitation is still pending. so you can log in to the admin portal with the account that is invited, go to 'invite' and accept the invitation @Aliang-code

this works

**Comment by sylarevan** [comment]
Hi there. I'm just testing a selfhosted installation of AppFlowly, and as far as I can see, workspace invitation by mail is still not working. I have correctly set the `APPFLOWY_MAILER_SMTP_*` variables in the `.env` file, still I I can see in my `appflowy-cloud-appflowy_cloud-1` container log:

`ERROR | timestamp=2024-11-29T14:55:09.704019Z fields={"message":"Failed to send workspace invite email: permanent error (550): 5.7.27 <sender@example.com>: Sender address rejected: Domain example.com does not accept mail (nullMX)\n\nCaused by:\n    5.7.27 <sender@example.com>: Sender address rejected: Domain example.com does not accept mail (nullMX)\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: appflowy_cloud::biz::workspace::ops::invite_workspace_members::{{closure}}::{{closure}}::{{closure}}::{{closure}}\n   2: tokio::runtime::task::raw::poll\n   3: std::sys_common::backtrace::__rust_begin_short_backtrace\n   4: core::ops::function::FnOnce::call_once{{vtable.shim}}\n   5: std::sys::pal::unix::thread::Thread::new::thread_start\n   6: <unknown>\n   7: clone"} target=appflowy_cloud::biz::workspace::ops filename=src/biz/workspace/ops.rs line_number=473 
`

It seems the default `sender@example.com` values are used instead of the those in the `.env` file, or am I missing something?
