### ISSUE TITLE
[Bug] Unable to sign in when GOTRUE_DISABLE_SIGNUP=true

### ISSUE THREAD

**Issue by DrilealoTatarara** [AppFlowy-IO/AppFlowy-Cloud#562]
**Describe the bug**
I want to deny the signups from the admin panel to every who has not an invitation. They told me in the discord that if i added the line "GOTRUE_DISABLE_SIGNUP=true" to the enviroment variables in docker-compose.yml in gotrues configuration, the sign ups whould be blocked. That worked, the problem is that existing users can't log in. There appears  an error in the screen:

![error-log-in](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/144098726/ee6d283b-affd-446c-be57-1a765f3c4439)

**Comment by speed2exe** [comment]
@DrilealoTatarara thanks for letting us know. this a popular requested feature and we will look into it

**Comment by Svyatopes** [comment]
Any updates?

**Comment by speed2exe** [comment]
@Svyatopes @DrilealoTatarara it appears that `appflowy-cloud` service is not running properly in the docker compose set up, do check the logs and errors, it should give you a reason why that fails

**Comment by D1reW0lf** [comment]
Hi.
Just to add my "me too" to this problem. 
Right now, I can either expose publicly my instance or not be able to log in at all.

**Comment by khorshuheng** [comment]
This has been fixed by https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/1034 . For new deployment using the latest appflowy gotrue image and docker compose file, setting GOTRUE_DISABLE_SIGNUP=true should no longer cause appflowy cloud to crash.

For existing deployment, since the admin client is already created, users should be able to set GOTRUE_DISABLE_SIGNUP from false to true without issue.
