### ISSUE TITLE
[Bug] Unable to access admin account when `GOTRUE_MAILER_AUTOCONFIRM` is false

### ISSUE THREAD

**Issue by DenuxPlays** [AppFlowy-IO/AppFlowy-Cloud#828]
**Describe the bug**

When I set `GOTRUE_MAILER_AUTOCONFIRM` to false and change the admin e-mail the account is unusable.
You cannot login.

**To Reproduce**
1. Change `GOTRUE_MAILER_AUTOCONFIRM` to false
2. Change `GOTRUE_ADMIN_EMAIL` to not a default one
3. Try to login

**Expected behavior**

The admin account should be enabled by default.

**Screenshots**

///

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Version 0.6.21

**Additional context**

///

**Comment by speed2exe** [comment]
@DenuxPlays This is expected behaviour. if you would like to change the admin email after initial deployment, you should delete the existing admin account, set `GOTRUE_MAILER_AUTOCONFIRM` to true, restart the docker services. then set the `GOTRUE_MAILER_AUTOCONFIRM` to false again to enforce mailer configuration.

**Comment by DenuxPlays** [comment]
Okay still seems pretty weird

Wouldn't it then be possible to send an email to the admin account if `GOTRUE_MAILER_AUTOCONFIRM` is set to true? (At least that was what I kind of expected)

**Comment by speed2exe** [comment]
@DenuxPlays it should, but this will mean that there are 2 admin accounts, which may not be desired
